# COMPLETE UPDATED LEASE AGREEMENT with Cape Town 2025 compliance improvements
# Variable assignments (fill in these with the specific details)
lessor_name = "Daniel Jonathan Pons"
lessor_address = "17 Nares Street, Observatory, 7925"
lessor_email = "djpons.10@gmail.com"
lessee_name = "Chad Van Rensburg"
lessee_id = "9404020237082"
lessee_email = "chad@example.com"
lessee_phone = "+27 83 965 6885"
premises_description = "Room 2, 17 Nares Street, Observatory, Cape Town, 7925"
commencement_date = "1 December 2023"
lease_months = 6
lease_period_words = "six"
termination_date = "31 May 2024"
deposit_full = 10500
deposit_full_words = "Ten Thousand Five Hundred South African Rand"
initial_deposit = 5250
initial_deposit_words = "Five Thousand Two Hundred and Fifty South African Rand"
initial_deposit_days = 7
second_deposit = 5250
second_deposit_words = "Five Thousand Two Hundred and Fifty South African Rand"
second_deposit_days = 30
rental_amount = 7000
rental_amount_words = "Seven Thousand Rand"
rental_due_day = "28th"
penalty_late = 150
penalty_late_words = "One Hundred and Fifty Rand"
interest_rate_above_prime = 3
rent_escalation_percent = 6  # Annual CPI-linked increase
max_people = 2
max_people_words = "Two"
breach_remedy_days = 7
lessee_domicilium_physical = "4 Arendblom, Middleton, Caledon, South Africa, 7230"
lessee_domicilium_email = lessee_email
lessor_domicilium_physical = lessor_address
lessor_domicilium_email = lessor_email
bank_account_holder = "MR DANIEL DJ PONS"
bank_name = "Standard Bank"
bank_branch = "Rondebosch Branch"
account_number = "10 18 612 597 4"
branch_code = "5009"
swift_code = "SBZAZAJJ"
person_responsible_name = "Danielle Scheepers"
person_responsible_id = lessee_id
person_responsible_email = lessee_email
person_responsible_phone = lessee_phone
water_restriction_level = "2"  # Update from City of Cape Town website
current_date = "November 27, 2025"

# Additional variables for Appendix A & B
property_manager_name = "Daniel"
property_manager_phone = "+27 79 863 5604"
helping_contact_name = "Helen"
helping_contact_phone = "+268 7864 9638"  # Reverted to original formatting as requested
security_company = "Premier Security"
cleaning_frequency = "once every two weeks"
cleaning_day = "Saturday mornings"
visitor_max_nights = 4
noise_weekday_cutoff = "9pm"
noise_weekend_cutoff = "11pm"
warnings_before_eviction = 3
wifi_type = "Uncapped Fibre Wi-Fi"